feat(api): use tv-pairing-code service
Qminder/swift-api pull request #317
Opened 2023-03-01 13:04 UTC by stdevi

## Description of the change

This PR changes api so that `tv/code` and `tv/code/{code}` requests are sent to the new tv pairing code service.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (Changed implementation, but existing functionality and APIs are not changed)

## Checklists

### Code review 

- [ ] Changes have been reviewed by at least one other engineer

2023-03-01 13:04 UTC, stdevi commented on Sources/QminderAPI.swift
> +    private var tvPairingServerAddress: String
Added tvPairingServerAddress

2023-03-01 13:05 UTC, stdevi commented on Sources/QminderAPI.swift
> +                tvPairingServerAddress: String = "https://tv.qminder.com") {
Set the value of `tvPairingServerAddress`

2023-03-01 13:06 UTC, stdevi commented on Sources/QminderAPI.swift
> +            fetchTvPairing(.tvCode, decodingType: TVPairingCode.self) { result, response in
It calls `fetchTvPairing` now

2023-03-01 13:07 UTC, stdevi commented on Sources/QminderAPI.swift
>      }
Added this function

2023-03-01 13:07 UTC, stdevi commented on Sources/QminderAPI.swift
>      }
Added this function

2023-03-02 09:55 UTC, 2ndalpha requested changes

2023-03-02 09:55 UTC, 2ndalpha commented on Sources/QminderAPI.swift
> +  /// Qminder TV Pairig Code address
Typo: Pairig

2023-03-02 10:35 UTC, stdevi commented on Sources/QminderAPI.swift
> +  /// Qminder TV Pairig Code address
Fixed

2023-03-02 10:58 UTC, 2ndalpha approved these changes
🚀

2023-03-02 11:16 UTC, merged